### ISSUE TITLE
If the amplitude of the narrowband signal source is changed to all 1 multi-target Angle measurement effect is very poor, why is this?

### ISSUE THREAD

**Issue by Inspirational-boy** [msamsami/doa-estimation-music#4]
Two signal sources:
s = sqrt(sVar)*randn(N, p).*exp(1i*(2*pi*fc*repmat([1:p]/fs, N, 1)));
s = sqrt(sVar)*exp(1i*(2*pi*fc*repmat([1:p]/fs, N, 1)));

![Uploading untitled.jpg…]()
![Uploading untitled1.jpg…]()

**Comment by msamsami** [comment]
Hi @Inspirational-boy 

Images aren't uploaded. Please post the images correctly and send more details about your signal sources, so I can follow up on your issue.

**Comment by Inspirational-boy** [comment]
hi @msamsami 
I understand that one is a coherent source and one is an incoherent source.

**Comment by msamsami** [comment]
@Inspirational-boy 

The first equation represents an incoherent source where the signals from different sources are independent, and each source's signal has a Gaussian amplitude distribution with variance `sVar`. The second equation, however, represents a coherent source where each source signal has a constant amplitude (`sqrt(sVar)`). When all the signal sources have the same constant amplitude, it reduces the diversity among the signals received by the array sensors. In such cases, the signals become more correlated (coherent), making it challenging for the MUSIC algorithm to differentiate between them effectively. This is because MUSIC relies on the orthogonality between the signal and noise subspaces, and high signal coherence can disrupt this orthogonality, leading to poor DOA estimation.

Therefore, when the amplitude of the narrowband signal source is changed to all 1, making the multi-target angle measurement with the MUSIC algorithm might yield poor results due to the increased signal coherence. The performance degradation occurs because the MUSIC algorithm assumes the sources are uncorrelated, and high coherence violates this assumption. In contrast, the MUSIC algorithm can more easily distinguish between the sources for incoherent sources with random amplitudes, leading to better DOA estimation performance.
